### ISSUE TITLE
tasoller - fn1 and fn2 doesnt work in game

### ISSUE THREAD

**Issue by musani0601** [CrazyRedMachine/chu2to3#1]
well it does work but after starting a song fn2 will stop putting in credits, and fn1 (test mode) only works once (after that it doesn't let me go to the menu anymore)

**Comment by CrazyRedMachine** [comment]
can you try again with this version to see if it solves the issue? looks like the original chuniio.dll handles opbtn differently from beams for some reason.

[chu2to3tasollertest.zip](https://github.com/CrazyRedMachine/chu2to3/files/8893398/chu2to3tasollertest.zip)

**Comment by musani0601** [comment]
Sorry for the late reply, this fixed it for me and fn1/fn2 works now :)
