### ISSUE TITLE
Please add NEW+ support

### ISSUE THREAD

**Issue by C029s-MOC** [CrazyRedMachine/chu2to3#2]
Hardware=Yubideck Software=NEW+  NOT WORKING AT ALL
Deck does not change to black + Air does not change color when game starts (indicating the deck is not connected to the game)
Please suggest possible fixes to this problem (First time using NEW+)

**Comment by CrazyRedMachine** [comment]
hi,
yubideck has been tested on new+ during dev so I confirm it should work.

do you have yubideck chuniio.dll working properly with plost? did you add it to the new+ directory alongside chu2to3 dlls? did you set the chu2to3 paths in the .ini properly? are you using the correct tools version?
